name: ZMK Firmware Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ZMK Config
        uses: actions/checkout@v3
        with:
          path: config

      - name: Checkout ZMK Firmware
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install West + Dependencies
        run: |
          pip install west
          west init -l config
          west update
          west zephyr-export
          pip install -r zmk/app/requirements.txt

      - name: Build Left Half
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=robinkey -DZMK_CONFIG=$(pwd)/config

      - name: Upload Left Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware-left
          path: build/zephyr/zmk.uf2

      - name: Clean Build
        run: rm -rf build

      - name: Build Right Half
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=robinkey -DZMK_CONFIG=$(pwd)/config -DSHIELD_RIGHT=1

      - name: Upload Right Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware-right
          path: build/zephyr/zmk.uf2

          Fix broken workflow – replace reuse with inline
